name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Run unit tests (fast)
        run: |
          python -m pytest tests/ -q -k "not integration" --junitxml=reports/junit.xml --cov=app --cov-report=xml
      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: pytest-reports
          path: reports

  integration-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v2
      - name: Bring up services (integration)
        run: |
          docker compose -f docker-compose.yml up -d --build
          sleep 10
      - name: Run integration tests
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          python -m pytest tests/ -v -m integration --junitxml=reports/integration-junit.xml
      - name: Tear down
        run: |
          docker compose -f docker-compose.yml down
      - name: Upload integration reports
        uses: actions/upload-artifact@v4
        with:
          name: integration-reports
          path: reports/integration-junit.xml
